### ISSUE TITLE
API Exception 404

### ISSUE THREAD

**Issue by kfeine** [Netflix/stethoscope#21]
Hi,

I want to install Stethoscope on a Debian 8 server. I basically followed those steps:

1. Install node.js and python3-virtualenv
2. Clone the repo
3. Create a virtualenv and install backend using `make develop`
4. Compile frontend using `make react-build`
5. Adapt the nginx configuration file to the correct path
6. Run backend using `stethoscope-login runserver -p 5002` and `twistd -n web -p 5001 --class=stethoscope.api.resource.resource`

Now I can see the UI interface, with the message "Error loading notifications" and a redirection to "/user%40example.com". I've got this error on the API stdout:

```
2017-04-13T14:08:14+0200 [-] Site starting on 5001
2017-04-13T14:08:14+0200 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site object at 0x7f11ec378780>
2017-04-13T14:08:28+0200 [stderr#error] [2017-04-13 12:08:28.673352] ERROR: stethoscope.api.factory: Exception: 404: Not Found
2017-04-13T14:08:28+0200 [stderr#error] Traceback (most recent call last):
2017-04-13T14:08:28+0200 [stderr#error]   File "/data/services/web/stethoscope/stethoscope-venv/lib/python3.4/site-packages/twisted/web/http.py", line 766, in requestReceived
2017-04-13T14:08:28+0200 [stderr#error]     self.process()
2017-04-13T14:08:28+0200 [stderr#error]   File "/data/services/web/stethoscope/stethoscope-venv/lib/python3.4/site-packages/twisted/web/server.py", line 190, in process
2017-04-13T14:08:28+0200 [stderr#error]     self.render(resrc)
2017-04-13T14:08:28+0200 [stderr#error]   File "/data/services/web/stethoscope/stethoscope-venv/lib/python3.4/site-packages/twisted/web/server.py", line 241, in render
2017-04-13T14:08:28+0200 [stderr#error]     body = resrc.render(self)
2017-04-13T14:08:28+0200 [stderr#error]   File "/data/services/web/stethoscope/stethoscope-venv/lib/python3.4/site-packages/klein/resource.py", line 201, in render
2017-04-13T14:08:28+0200 [stderr#error]     d = defer.maybeDeferred(_execute)
2017-04-13T14:08:28+0200 [stderr#error] --- <exception caught here> ---
2017-04-13T14:08:28+0200 [stderr#error]   File "/data/services/web/stethoscope/stethoscope-venv/lib/python3.4/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
2017-04-13T14:08:28+0200 [stderr#error]     result = f(*args, **kw)
2017-04-13T14:08:28+0200 [stderr#error]   File "/data/services/web/stethoscope/stethoscope-venv/lib/python3.4/site-packages/klein/resource.py", line 179, in _execute
2017-04-13T14:08:28+0200 [stderr#error]     (rule, kwargs) = mapper.match(return_rule=True)
2017-04-13T14:08:28+0200 [stderr#error]   File "/data/services/web/stethoscope/stethoscope-venv/lib/python3.4/site-packages/werkzeug/routing.py", line 1563, in match
2017-04-13T14:08:28+0200 [stderr#error]     raise NotFound()
2017-04-13T14:08:28+0200 [stderr#error] werkzeug.exceptions.NotFound: 404: Not Found
```

Did I missed some configuration or dependency?

Thanks, you're project seems great and I can't wait to use it ;)
Kind regards,

**Comment by andrewmwhite** [comment]
Thanks for the report. I'm looking into this, but I'll note off the bat that we haven't done much testing on Python 3 nor on stock Debian.

**Comment by andrewmwhite** [comment]
I'm so far unable to replicate this issue. I'll keep digging into it but it may be next week before I have much time to do so.

**Comment by andrewmwhite** [comment]
I still haven't been able to replicate this exact issue. However, #23 does fix a Python 3 issue which may be related. If you could give the current master a try an let me know if it fixes your issue, that would be great.

**Comment by kfeine** [comment]
Hi,

I pulled the repo and retried but the result is still the same. I will try to reinstall from scratch and let you know if it persists.

Kind regards,

**Comment by andrewmwhite** [comment]
I'll should have some time early next week to attempt to reproduce this on an actual Debian image. I'll report back once I've done so.

**Comment by andrewmwhite** [comment]
I was finally able to replicate this. The issue, I suspect, is that you haven't configured any notification plugins. I'll work on improving the log messaging to indicate when this is the case.

**Comment by andrewmwhite** [comment]
Closing since it's been 7 days without a response.
